package za.ac.cput.factory;
/* ReportFactoryTest.java

   Report Factory Testing class

   Author: Alakhe Mxakato (230485316)

   Date: 28 June 2026
*/
import org.junit.jupiter.api.*;
import za.ac.cput.domain.*;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class ReportFactoryTest {

    @Test
    @Order(1)
    @DisplayName("Should create basic report")
    void createReport() {
        Report report = ReportFactory.createReport("SALES", "Admin", "PDF");

        assertNotNull(report);
        assertEquals("SALES", report.getReportType());
        assertEquals("Admin", report.getGeneratedBy());
        assertEquals("PDF", report.getFormat());
        assertNotNull(report.getGeneratedDate());

        System.out.println("=== Basic Report ===");
        System.out.println("Type: " + report.getReportType());
        System.out.println("Generated By: " + report.getGeneratedBy());
        System.out.println("Format: " + report.getFormat());
    }

    @Test
    @Order(2)
    @DisplayName("Should create report with data")
    void createReportWithData() {
        byte[] data = "Test report data".getBytes();
        Report report = ReportFactory.createReportWithData("BOOKINGS", "Admin", "EXCEL", data);

        assertNotNull(report);
        assertNotNull(report.getData());
        assertEquals(data.length, report.getData().length);

        System.out.println("=== Report with Data ===");
        System.out.println("Data size: " + report.getData().length + " bytes");
    }


    @Test
    @Order(3)
    @DisplayName("Should throw exception when report type is empty")
    void showExceptionWhenReportTypeEmpty() {
        assertThrows(IllegalArgumentException.class, () ->
                ReportFactory.createReport("", "Admin", "PDF")
        );
        System.out.println("✓ Empty report type correctly rejected");
    }

    @Test
    @Order(4)
    @DisplayName("Should throw exception when generated by is empty")
    void showExceptionWhenGeneratedByEmpty() {
        assertThrows(IllegalArgumentException.class, () ->
                ReportFactory.createReport("SALES", "", "PDF")
        );
        System.out.println("✓ Empty generated by correctly rejected");
    }

    @Test
    @Order(5)
    @DisplayName("Should generate report")
    void testGenerate() {
        Report report = ReportFactory.createReport("SALES", "Admin", "PDF");
        report.generate();
        assertNotNull(report.getGeneratedDate());
        System.out.println("✓ Report generated at: " + report.getGeneratedDate());
    }
}