package za.ac.cput.factory;
/* ReportFactory.java

   Report Factory class

   Author: Alakhe Mxakato (230485316)

   Date: 28 June 2026
*/
import za.ac.cput.domain.Report;
import za.ac.cput.util.Helper;
import za.ac.cput.util.IdGenerator;

import java.time.LocalDateTime;
import java.util.HashMap;

public class ReportFactory {

    private static final IdGenerator idGenerator = new IdGenerator();

    /**
     * Creates a basic report
     */
    public static Report createReport(String reportType, String generatedBy, String format) {
        Helper.requireNotEmptyOrNull(reportType, "Report Type");
        Helper.requireNotEmptyOrNull(generatedBy, "Generated By");
        Helper.requireNotEmptyOrNull(format, "Format");

        String reportId = idGenerator.generateId("RPT");

        return new Report.Builder()
                .setReportId(reportId)
                .setReportType(reportType)
                .setGeneratedBy(generatedBy)
                .setFormat(format)
                .setGeneratedDate(LocalDateTime.now())
                .build();
    }

    /**
     * Creates a report with data
     */
    public static Report createReportWithData(String reportType, String generatedBy,
                                              String format, byte[] data) {
        Helper.requireNonNull(data, "Data");

        Report report = createReport(reportType, generatedBy, format);

        return new Report.Builder()
                .copy(report)
                .setData(data)
                .build();
    }


}
